# -*- coding: utf-8 -*-
"""13barras_OPF_CPLEX.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zM6eVBV_zukOJLLOcxciuMUXhXxnndxl

V19022026 : Problema muito grande para cplex
"""

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# import sys
# import os
# 
# if 'google.colab' in sys.modules:
#     !pip install idaes-pse --pre
#     !idaes get-extensions --to ./bin
#     os.environ['PATH'] += ':bin'
#

from google.colab import drive
drive.mount('/content/drive', force_remount=True)

import shutil
import sys
import os.path

if not shutil.which("pyomo"):
    !pip install -q pyomo
    assert(shutil.which("pyomo"))

if not (shutil.which("ipopt") or os.path.isfile("ipopt")):
    if "google.colab" in sys.modules:
        !wget -N -q "https://matematica.unipv.it/gualandi/solvers/ipopt-linux64.zip"
        !unzip -o -q ipopt-linux64
    else:
        try:
            !conda install -c conda-forge ipopt
        except:
            pass

# Commented out IPython magic to ensure Python compatibility.
# # Source - https://stackoverflow.com/a/75924403
# # Posted by Bethany Nicholson
# # Retrieved 2026-02-05, License - CC BY-SA 4.0
# 
# %%capture
# import sys
# import os
# 
# if 'google.colab' in sys.modules:
#     !pip install idaes-pse --pre
#     !idaes get-extensions --to ./bin
#     os.environ['PATH'] += ':bin'
#

# Source - https://stackoverflow.com/a/76164050
# Posted by Corralien, modified by community. See post 'Timeline' for change history
# Retrieved 2026-02-09, License - CC BY-SA 4.0

# Create an environment with your WLS license
# params = {
# "WLSACCESSID": 'cf2dc101-2872-496c-bfd2-42ce1cdc74d2',
# "WLSSECRET": 'ddb2b430-f7d6-4651-aa3e-69f162a6aa35',
# "LICENSEID":2776820,
# }

# import os

# os.environ['GRB_WLSACCESSID'] = 'cf2dc101-2872-496c-bfd2-42ce1cdc74d2'
# os.environ['GRB_WLSSECRET']   = 'ddb2b430-f7d6-4651-aa3e-69f162a6aa35'
# os.environ['GRB_LICENSEID']  = '2776820'

# if not (shutil.which("glpk") or os.path.isfile("glpk")):
#     if "google.colab" in sys.modules:
#         !apt-get install -y -qq glpk-utils
#     else:
#         try:
#             !conda install -c conda-forge glpk
#         except:
#             pass

!rm -rf ACOPF
!git clone https://github.com/DarleneJD/ACOPF.git

import math
import numpy as np
import pandas as pd
import pyomo.environ as pyo
from pyomo.opt import SolverFactory

"""# Carregar e processar dados"""

base_path = "/content/ACOPF"

def normalize_phases(value):
    """
    Converte entradas como:
    1
    1.0
    '1,2,3'
    '1.0,2.0,3.0'
    '1.2.3'
    em lista de inteiros [1], [1,2,3]
    """
    if pd.isna(value):
        return []

    s = str(value).strip()

    # unifica separadores
    s = s.replace(".", ",")
    parts = [p.strip() for p in s.split(",") if p.strip() != ""]

    phases = []
    for p in parts:
        try:
            ph = int(float(p))
            if ph in [1, 2, 3]:
                phases.append(ph)
        except ValueError:
            pass

    return sorted(set(phases))

branches_path = f"{base_path}/branches_1.xlsx"
buses_path = f"{base_path}/buses_1.xlsx"

DT_MIN = 10  # min
T = list(range(0, 15))  # 24h com 10 min -> 144 passos (use 144, evita bugs)
PHASES = [1, 2, 3]

# MT - Média Tensão
df_branches_mt = pd.read_excel(branches_path, sheet_name="MT")
df_buses_mt = pd.read_excel(buses_path, sheet_name="MT")
df_buses_mt = df_buses_mt[~df_buses_mt["name"].astype(str).str.contains("Source", case=False)]

# BT - Baixa Tensão
df_branches_bt = pd.read_excel(branches_path, sheet_name="BT")
df_buses_bt = pd.read_excel(buses_path, sheet_name="BT")

# Transformadores
df_trafos = pd.read_excel(branches_path, sheet_name="Trafos")
df_trafos.columns = df_trafos.columns.str.strip()

# PV
df_pv = pd.read_excel(buses_path, sheet_name="PV")

#
# NORMALIZAÇÃO DAS FASES

df_branches_mt['phase_list'] = df_branches_mt['phase'].apply(normalize_phases)
df_branches_bt['phase_list'] = df_branches_bt['phase'].apply(normalize_phases)
df_trafos['phase_list'] = df_trafos['phases'].apply(normalize_phases)
df_buses_mt['phase_list'] = df_buses_mt['phases'].apply(normalize_phases)
df_buses_bt['phase_list'] = df_buses_bt['phases'].apply(normalize_phases)
df_pv['phase_list'] = df_pv['phases'].apply(normalize_phases)


# MAPEAMENTO BARRAS MT

bus_id_mt = dict(zip(df_buses_mt['name'], df_buses_mt['N']))
slack_bus = df_buses_mt.loc[df_buses_mt["tb"] == 3, "N"].iloc[0]
buses_mt = df_buses_mt["N"].astype(int).unique().tolist()


# MAPEAMENTO BARRAS BT

bus_id_bt = dict(zip(df_buses_bt['name'], df_buses_bt['N']))
buses_bt = df_buses_bt["N"].astype(int).unique().tolist()


# PREPARAÇÃO RAMOS MT

# Remover ramo MT 650->RG60 (Não é ramo, é SVR)
df_branches_mt = df_branches_mt[
    ~((df_branches_mt["l"].astype(str) == "650") & (df_branches_mt["k"].astype(str) == "RG60"))
].copy()



# Converter barras l,k para identificador numérico
df_branches_mt['from_bus'] = df_branches_mt['l'].map(bus_id_mt)
df_branches_mt['to_bus'] = df_branches_mt['k'].map(bus_id_mt)

# Remover ramos mal mapeados
df_branches_mt = df_branches_mt.dropna(subset=['from_bus', 'to_bus'])

df_branches_mt['from_bus'] = df_branches_mt['from_bus'].astype(int)
df_branches_mt['to_bus'] = df_branches_mt['to_bus'].astype(int)
df_branches_mt['m'] = df_branches_mt['m'].astype(int)
df_branches_mt['Imax'] = df_branches_mt['Imax'].astype(int)

branches_mt = df_branches_mt["m"].unique().tolist()


# PREPARAÇÃO RAMOS BT

df_branches_bt['from_bus'] = df_branches_bt['l'].map(bus_id_bt)
df_branches_bt['to_bus'] = df_branches_bt['k'].map(bus_id_bt)
df_branches_bt = df_branches_bt.dropna(subset=['from_bus', 'to_bus'])

df_branches_bt['from_bus'] = df_branches_bt['from_bus'].astype(int)
df_branches_bt['to_bus'] = df_branches_bt['to_bus'].astype(int)
df_branches_bt['m'] = df_branches_bt['m'].astype(int)

branches_bt = df_branches_bt["m"].unique().tolist()


# CONJUNTOS POR FASE

PHASES = [1, 2, 3]

# Ramos MT por fase
branch_phase_mt = []
for _, row in df_branches_mt.iterrows():
    m = int(float(row["m"]))
    for ph in row["phase_list"]:
        branch_phase_mt.append((m, ph))
branch_phase_mt = sorted(set(branch_phase_mt))

# Ramos BT por fase
branch_phase_bt = []
for _, row in df_branches_bt.iterrows():
    m = int(float(row["m"]))
    for ph in row["phase_list"]:
        branch_phase_bt.append((m, ph))
branch_phase_bt = sorted(set(branch_phase_bt))

# Barras BT por fase
bus_phase_bt = sorted({
    (int(row["N"]), ph)
    for _, row in df_buses_bt.iterrows()
    for ph in row["phase_list"]
})


# PARÂMETROS RAMOS MT
R_mt, X_mt, Imax_mt = {}, {}, {}
from_bus_mt, to_bus_mt, Length_mt, Vbase_mt, Smax_mt = {}, {}, {}, {}, {}

for _, row in df_branches_mt.iterrows():
    m = int(float(row["m"]))
    from_bus_mt[m] = int(row["from_bus"])
    to_bus_mt[m] = int(row["to_bus"])
    Imax_mt[m] = float(row["Imax"])
    Length_mt[m] = float(row["Length_m"])

    # Vbase por ramo
    fb = from_bus_mt[m]
    Vbase_mt[m] = float(df_buses_mt.loc[df_buses_mt["N"] == fb, "v_nom_kv"].iloc[0])
    Smax_mt[m] = Vbase_mt[m] * Imax_mt[m]  # kVA por fase

    # Parâmetros por fase
    for ph in row["phase_list"]:
        R_mt[(m, ph)] = float(row["R"])
        X_mt[(m, ph)] = float(row["X"])


# PARÂMETROS RAMOS BT
R_bt, X_bt, Imax_bt = {}, {}, {}
from_bus_bt, to_bus_bt, Vbase_bt, Smax_bt = {}, {}, {}, {}

for _, row in df_branches_bt.iterrows():
    m = int(float(row["m"]))
    from_bus_bt[m] = int(row["from_bus"])
    to_bus_bt[m] = int(row["to_bus"])
    Imax_bt[m] = float(row["Imax"])

    # Vbase por ramo
    fb = from_bus_bt[m]
    Vbase_bt[m] = float(df_buses_bt.loc[df_buses_bt["N"] == fb, "v_nom_kv"].iloc[0])
    Smax_bt[m] = Vbase_bt[m] * Imax_bt[m]


# CARGA BT
Pload_bt, Qload_bt = {}, {}

for _, row in df_buses_bt.iterrows():
    b = int(row["N"])
    phs = row["phase_list"]
    if len(phs) == 0:
        continue

    Pd = float(row["P_D"]) if not pd.isna(row["P_D"]) else 0.0
    Qd = float(row["Q_D"]) if not pd.isna(row["Q_D"]) else 0.0

    share = 1.0 / len(phs)

    for ph in phs:
        Pload_bt[(b, ph)] = Pd * share
        Qload_bt[(b, ph)] = Qd * share


# PV
# ============================================================
# (i) PV — BLOCO FINAL DE CARREGAMENTO (sheet "PV")
#     Saídas: Ppv_max[(bus,ph)], Sinv_ph[(bus,ph)], pf_nom[(bus,ph)]
# ============================================================
df_pv = pd.read_excel(buses_path, sheet_name="PV")
df_pv.columns = df_pv.columns.str.strip()

# normaliza fases (coluna "phases")
df_pv["phase_list"] = df_pv["phases"].apply(normalize_phases)

# limpa strings
df_pv["Name"] = df_pv["Name"].astype(str).str.strip()
df_pv["Bus"]  = df_pv["Bus"].astype(str).str.strip()

# converte numéricos úteis
for c in ["kva", "pf", "kV"]:
    if c in df_pv.columns:
        df_pv[c] = pd.to_numeric(df_pv[c], errors="coerce")

for ph in [1, 2, 3]:
    pc = f"p_pv_{ph}"
    qc = f"q_pv_{ph}"
    if pc in df_pv.columns:
        df_pv[pc] = pd.to_numeric(df_pv[pc], errors="coerce")
    if qc in df_pv.columns:
        df_pv[qc] = pd.to_numeric(df_pv[qc], errors="coerce")

# mapear PV -> barra numérica BT (N)
df_pv["busN"] = df_pv["Bus"].map(bus_id_bt)
df_pv = df_pv.dropna(subset=["busN"]).copy()
df_pv["busN"] = df_pv["busN"].astype(int)

# dicionários por (bus,ph)
Ppv_max = {}   # kW por fase
Sinv_ph = {}   # kVA por fase (rating físico por fase)
pf_nom  = {}   # opcional

for _, row in df_pv.iterrows():
    bus = int(row["busN"])
    phs = row["phase_list"]
    if len(phs) == 0:
        continue

    # rating do inversor (kVA) do equipamento → divide nas fases conectadas
    S_total = float(row["kva"]) if ("kva" in row and not pd.isna(row["kva"])) else 0.0
    S_per_phase = S_total / len(phs) if len(phs) > 0 else 0.0

    # pf nominal (opcional; hoje não entra nas restrições)
    pf_val = float(row["pf"]) if ("pf" in row and not pd.isna(row["pf"])) else 1.0

    for ph in phs:
        pcol = f"p_pv_{ph}"
        Pmax = float(row[pcol]) if (pcol in df_pv.columns and not pd.isna(row[pcol])) else 0.0

        Ppv_max[(bus, ph)] = max(0.0, Pmax)
        Sinv_ph[(bus, ph)] = max(0.0, S_per_phase)
        pf_nom[(bus, ph)]  = pf_val

irr_hourly = [
    0,0,0,0,0,0,
    0.037761984,
    0.169961411,
    0.384597675,
    0.433180475,
    0.7358863,
    0.620398116,
    0.499184575,
    0.5805312,
    0.446405999,
    0.369826579,
    0.160755516,
    0.041860959,
    0,0,0,0,0,0
]
nT = len(T)
x_hour = np.linspace(0, 1, len(irr_hourly))
x_full = np.linspace(0, 1, nT)

irr_interp = np.interp(x_full, x_hour, irr_hourly)

irr_dict = {t: float(irr_interp[t]) for t in range(nT)}


# TRANSFORMADORES
# 1. Primeiro, filtrar o DataFrame de transformadores ANTES de criar os conjuntos
df_trafos = df_trafos[df_trafos["trafo_id"] != "Sub"].copy()

# 2. Agora, com o DataFrame filtrado, criar todos os conjuntos
TR = sorted(df_trafos["trafo_id"].unique().tolist())
TR_PH = sorted({
    (tid, ph)
    for _, row in df_trafos.iterrows()
    for tid, phs in [(row["trafo_id"], row["phase_list"])]
    for ph in phs
})

# 3. Recalcular tudo que depende dos transformadores
# Número de fases por transformador
nph_TR = {row.trafo_id: len(row.phase_list) for _, row in df_trafos.iterrows()}

# Potência nominal total (kVA)
Pnom_TR = {row.trafo_id: float(row.kva) for _, row in df_trafos.iterrows()}

# Perdas a vazio (kW)
Pfe_TR = {row.trafo_id: float(row["Perdas Vazio kW"]) for _, row in df_trafos.iterrows()}

# Perdas totais (kW)
Pt_TR = {row.trafo_id: float(row["Perdas Totais kW"]) for _, row in df_trafos.iterrows()}

# Perdas no cobre totais
Pcu_TR = {tid: Pt_TR[tid] - Pfe_TR[tid] for tid in Pnom_TR}

# Perdas no cobre por fase
Pcu_TR_PH = {}
Snom_TR_PH = {}

for _, row in df_trafos.iterrows():
    tid = row.trafo_id
    for ph in row.phase_list:
        Pcu_TR_PH[(tid, ph)] = Pcu_TR[tid] / nph_TR[tid]
        Snom_TR_PH[(tid, ph)] = Pnom_TR[tid] / nph_TR[tid]

# Perda a vazio por fase
Pfe_TR_PH = {
    (row.trafo_id, ph): Pfe_TR[row.trafo_id] / nph_TR[row.trafo_id]
    for _, row in df_trafos.iterrows()
    for ph in row.phase_list
}

# Coeficientes de perdas
alpha_tr = {}  # coef perdas P
beta_tr = {}   # coef perdas Q

for _, row in df_trafos.iterrows():
    tid = row["trafo_id"]
    r_per = float(row["r_per"])/100.0 if ("r_per" in row and not pd.isna(row["r_per"])) else 0.0
    xhl = float(row["XHL"])/100.0 if ("XHL" in row and not pd.isna(row["XHL"])) else 0.0

    for ph in row["phase_list"]:
        alpha_tr[(tid, ph)] = r_per
        beta_tr[(tid, ph)] = xhl

# Potência nominal dos transformadores
Snom_TR = {
    row["trafo_id"]: float(row["kva"])
    for _, row in df_trafos.iterrows()
}

# 4. Criar dicionário de fases por transformador
trafo_phases_dict = {row["trafo_id"]: row["phase_list"] for _, row in df_trafos.iterrows()}

# # 5. Agora criar as barras virtuais apenas para os transformadores válidos
# base_tr_bus = 10_000
# trafo_MT_bus = {}
# trafo_BT_bus = {}

# for i, (_, row) in enumerate(df_trafos.iterrows()):
#     tid = row["trafo_id"]
#     trafo_MT_bus[tid] = base_tr_bus + 2 * i
#     trafo_BT_bus[tid] = base_tr_bus + 2 * i + 1

# # 6. Mapeamento entre trafos e barras reais (apenas transformadores válidos)
# trafo_to_mt_bus = {}
# trafo_to_bt_bus = {}

# for _, row in df_trafos.iterrows():
#     tid = row["trafo_id"]
#     mt_bus_name = row["mv_bus"]
#     bt_bus_name = row["lv_bus"]

#     if mt_bus_name in bus_id_mt:
#         trafo_to_mt_bus[tid] = bus_id_mt[mt_bus_name]
#     else:
#         print(f"AVISO: Barra MT '{mt_bus_name}' não encontrada para trafo {tid}")
#         # Definir um valor padrão
#         trafo_to_mt_bus[tid] = buses_mt[0] if buses_mt else -1

#     if bt_bus_name in bus_id_bt:
#         trafo_to_bt_bus[tid] = bus_id_bt[bt_bus_name]
#     else:
#         print(f"AVISO: Barra BT '{bt_bus_name}' não encontrada para trafo {tid}")
#         # Definir um valor padrão
#         trafo_to_bt_bus[tid] = buses_bt[0] if buses_bt else -1

# # 7. Criar conjuntos de barras incluindo virtuais (apenas transformadores válidos)
# all_mt_buses = buses_mt + [trafo_MT_bus[tid] for tid in TR]
# all_bt_buses = buses_bt + [trafo_BT_bus[tid] for tid in TR]

# garante numérico (evita '4,16' string, etc.)
df_trafos["kv_mv"] = pd.to_numeric(df_trafos["kv_mv"], errors="coerce")
df_trafos["kv_lv"] = pd.to_numeric(df_trafos["kv_lv"], errors="coerce")

# dicionários por trafo_id
kv_mv_dict = {
    row["trafo_id"]: float(row["kv_mv"])
    for _, row in df_trafos.iterrows()
}
kv_lv_dict = {
    row["trafo_id"]: float(row["kv_lv"])
    for _, row in df_trafos.iterrows()
}

# Regulador SVR
# - 3 SVRs (um por fase) entre 650 -> RG60 (lado regulado = RG60)
# - taps independentes por fase: [-16, +16], step = 0.00625 pu/tap
# - controle com delay = 15 min (com dt=10 min => 2 steps)
# - inclui LDC com R_LDC=3, X_LDC=9 (assumidos ótimos)
# - fecha fisicamente: adiciona fluxo P/Q do SVR na MT (como “ramo especial”)
# - rastreamento: tap[t], tap_up[t], tap_down[t]
# OBS: com tap Inteiro/binários -> MINLP (use bonmin/couenne/scip). Para IPOPT,
#      troque domain=Integers/Binary por Reals/UnitInterval (relaxação).

# -------------------------
# CONFIG DO SVR
# -------------------------
df_reg = pd.read_excel(branches_path, sheet_name="Reg")
df_reg.columns = df_reg.columns.str.strip()

# remove linhas vazias/sem id
# df_reg = df_reg.dropna(subset=["trafo_id", "mv_bus", "lv_bus", "phases"]).copy()
# df_reg["trafo_id"] = df_reg["trafo_id"].astype(str).str.strip()
# df_reg["mv_bus"]   = df_reg["mv_bus"].astype(str).str.strip()
# df_reg["lv_bus"]   = df_reg["lv_bus"].astype(str).str.strip()

# fase como inteiro (coluna "phases" tem um único valor numérico)
df_reg["ph"] = df_reg["phases"].apply(lambda x: int(float(x)))

# mapear buses MT (mv_bus/lv_bus são nomes do sheet MT)
df_reg["up_bus"] = df_reg["mv_bus"].map(bus_id_mt).astype(int)
df_reg["dn_bus"] = df_reg["lv_bus"].map(bus_id_mt).astype(int)

# conversões numéricas seguras
num_cols = ["kv_lv","kv_mv","kva","ptratio_V","ctprim_A","r_LDC_V","X_LDC_V","vreg_V","band_V",
            "LoadLoss_per","Delay_s","maxtapchange","tapdelay_s","TapNum","Step"]
for c in num_cols:
    if c in df_reg.columns:
        df_reg[c] = pd.to_numeric(df_reg[c], errors="coerce")

# filtrar só SVRs válidos (fase 1..3)
df_reg = df_reg[df_reg["ph"].isin([1,2,3])].copy()

# conjuntos e dicionários
REG_PH = sorted([(row["trafo_id"], int(row["ph"])) for _, row in df_reg.iterrows()])
REG = sorted(df_reg["trafo_id"].unique().tolist())

reg_up_bus = {row["trafo_id"]: int(row["up_bus"]) for _, row in df_reg.iterrows()}
reg_dn_bus = {row["trafo_id"]: int(row["dn_bus"]) for _, row in df_reg.iterrows()}

# parâmetros elétricos e controle
kv_lv_dict_svr   = {row["trafo_id"]: float(row["kv_lv"]) for _, row in df_reg.iterrows()}  # kV fase-neutro (ex: 4.16/sqrt(3))
kv_mv_dict_svr   = {row["trafo_id"]: float(row["kv_mv"]) for _, row in df_reg.iterrows()}  # kV fase-neutro (ex: 4.16/sqrt(3))
kva_dict_svr     = {row["trafo_id"]: float(row["kva"]) for _, row in df_reg.iterrows()}
tapnum_dict  = {row["trafo_id"]: int(row["TapNum"]) for _, row in df_reg.iterrows()}   # esperado 16
step_dict    = {row["trafo_id"]: float(row["Step"]) for _, row in df_reg.iterrows()}   # em pu

# LDC em volts -> (R,X) em ohms usando CT/PT (se existirem)
# r_LDC_V / X_LDC_V são "volts" de compensação. Aproximação: Vdrop = Isec * (R+ jX)  => R = V/I
# Isec = Iprim / CTprim (se ctprim for relação). Se seus dados já forem em V por Amp secundário, ajuste aqui.
R_LDC = {}
X_LDC = {}
for _, row in df_reg.iterrows():
    rid = row["trafo_id"]
    rV = float(row["r_LDC_V"]) if not np.isnan(row["r_LDC_V"]) else 0.0
    xV = float(row["X_LDC_V"]) if not np.isnan(row["X_LDC_V"]) else 0.0
    ct = float(row["ctprim"])  if ("ctprim" in row and not np.isnan(row["ctprim"])) else 1.0

    # heurística: se ctprim é A primários por 1A secundário, então Isec = Iprim/ct
    # e Vdrop(sec) por 1A sec -> ohms(sec)=V/A. Usamos direto rV e xV como ohms "equivalentes".
    # Se você preferir fixar R_LDC=3 e X_LDC=9 como antes, basta sobrescrever aqui.
    R_LDC[rid] = rV  # proxy
    X_LDC[rid] = xV  # proxy

# # vreg/band em volts -> pu (base kv_lv)
# vreg_pu = {}
# band_pu = {}
# for _, row in df_reg.iterrows():
#     rid = row["trafo_id"]
#     ph  = int(row["ph"])
#     kv_ph = float(row["kv_lv"]) if not np.isnan(row["kv_lv"]) else (float(pyo.value(model.Vnom_MT))/math.sqrt(3))
#     base_V = kv_ph * 1000.0
#     vreg_pu[(rid,ph)] = float(row["vreg_V"]) / base_V if not np.isnan(row["vreg_V"]) else 1.0
#     band_pu[(rid,ph)] = float(row["band_V"]) / base_V if not np.isnan(row["band_V"]) else 0.02

# delays
delay_min = {row["trafo_id"]: float(row["delay"]) for _, row in df_reg.iterrows() if "delay" in df_reg.columns}

# =========================
# 1) Bases (por fase)
# =========================
VBASE_MT_KV = 4.16 / math.sqrt(3)      # VLN
VBASE_BT_KV = 0.480 / math.sqrt(3)     # VLN

SBASE_3PH_KVA = 1000.0
SBASE_PH_KVA  = SBASE_3PH_KVA / 3.0

ZBASE_MT_OHM = (VBASE_MT_KV**2) / SBASE_PH_KVA
ZBASE_BT_OHM = (VBASE_BT_KV**2) / SBASE_PH_KVA

IBASE_MT_A = (SBASE_PH_KVA / VBASE_MT_KV) * 1000.0
IBASE_BT_A = (SBASE_PH_KVA / VBASE_BT_KV) * 1000.0

def pq_to_pu(x_kw_or_kvar, Sbase_ph_kVA=SBASE_PH_KVA):
    return float(x_kw_or_kvar) / Sbase_ph_kVA

def build_line_pu_dicts(df_branches, is_mt=True, rx_is_per_km=False):
    """
    Converte linhas para pu.
    - rx_is_per_km=False: df_branches['R','X'] já estão em ohm TOTAL do trecho (seu caso)
    - rx_is_per_km=True : df_branches['R','X'] estão em ohm/km e usa Length_m
    """
    Zbase = ZBASE_MT_OHM if is_mt else ZBASE_BT_OHM
    Ibase = IBASE_MT_A if is_mt else IBASE_BT_A

    R_pu, X_pu, Imax_pu = {}, {}, {}

    for _, row in df_branches.iterrows():
        m = int(float(row["m"]))
        Imax_A = float(row["Imax"])
        Imax_pu_m = Imax_A / Ibase

        L_km = float(row["Length_m"])/1000.0 if ("Length_m" in df_branches.columns and not pd.isna(row["Length_m"])) else 1.0

        for ph in row["phase_list"]:
            R_raw = float(row["R"])
            X_raw = float(row["X"])

            if rx_is_per_km:
                R_ohm = R_raw * L_km
                X_ohm = X_raw * L_km
            else:
                R_ohm = R_raw
                X_ohm = X_raw

            R_pu[(m, ph)] = R_ohm / Zbase
            X_pu[(m, ph)] = X_ohm / Zbase
            Imax_pu[(m, ph)] = Imax_pu_m

    return R_pu, X_pu, Imax_pu

# =========================
# 2) Linhas em pu (seu caso: R,X totais no trecho)
# =========================
R_mt_pu, X_mt_pu, Imax_mt_pu = build_line_pu_dicts(df_branches_mt, is_mt=True,  rx_is_per_km=False)
R_bt_pu, X_bt_pu, Imax_bt_pu = build_line_pu_dicts(df_branches_bt, is_mt=False, rx_is_per_km=False)

# =========================
# 3) Cargas e PV em pu (por fase)
# =========================
Pload_bt_pu = {(b, ph): pq_to_pu(P) for (b, ph), P in Pload_bt.items()}
Qload_bt_pu = {(b, ph): pq_to_pu(Q) for (b, ph), Q in Qload_bt.items()}

Ppv_max_pu = {(b, ph): pq_to_pu(P) for (b, ph), P in Ppv_max.items()}
Sinv_pu    = {(b, ph): float(S) / SBASE_PH_KVA for (b, ph), S in Sinv_ph.items()}  # pu (kVA/kVA)

# =========================
# 4) Trafos em pu (por fase)
# =========================
Pfe_TR_PH_pu  = {(tid, ph): pq_to_pu(v) for (tid, ph), v in Pfe_TR_PH.items()}
Pcu_TR_PH_pu  = {(tid, ph): pq_to_pu(v) for (tid, ph), v in Pcu_TR_PH.items()}
Snom_TR_PH_pu = {(tid, ph): float(v) / SBASE_PH_KVA for (tid, ph), v in Snom_TR_PH.items()}

"""# Modelo"""

m = pyo.ConcreteModel()

# ============================================================
# CONJUNTOS DO MODELO
# - Horizonte temporal
# - Fases
# - Barras reais + virtuais (transformadores)
# - Ramos por fase
# - Transformadores, Reguladores e PVs
# ============================================================

# ------------------------------------------------------------
# 1) Horizonte temporal e fases
# ------------------------------------------------------------
m.T  = pyo.Set(initialize=T, ordered=True, doc="Horizonte temporal")
m.PH = pyo.Set(initialize=PHASES, doc="Fases: 1=A, 2=B, 3=C")


# ------------------------------------------------------------
# 2) Barras virtuais de transformadores (somente TR válidos)
# ------------------------------------------------------------
base_tr_bus = 10_000

# IDs artificiais somente para os trafos em TR (já filtrados)
trafo_MT_bus = {tid: base_tr_bus + 2*i     for i, tid in enumerate(TR)}
trafo_BT_bus = {tid: base_tr_bus + 2*i + 1 for i, tid in enumerate(TR)}

# Mapeamento entre trafos e barras reais (somente TR válidos)
# (df_trafos aqui deve estar filtrado: df_trafos = df_trafos[df_trafos["trafo_id"] != "Sub"].copy())
trafo_to_mt_bus = {}
trafo_to_bt_bus = {}

# cria um índice rápido por trafo_id
df_trafos_idx = df_trafos.set_index("trafo_id")

for tid in TR:
    row = df_trafos_idx.loc[tid]

    mt_bus_name = str(row["mv_bus"]).strip()
    bt_bus_name = str(row["lv_bus"]).strip()

    if mt_bus_name not in bus_id_mt:
        raise KeyError(f"Barra MT '{mt_bus_name}' não encontrada para trafo {tid}")
    if bt_bus_name not in bus_id_bt:
        raise KeyError(f"Barra BT '{bt_bus_name}' não encontrada para trafo {tid}")

    trafo_to_mt_bus[tid] = int(bus_id_mt[mt_bus_name])
    trafo_to_bt_bus[tid] = int(bus_id_bt[bt_bus_name])




# ------------------------------------------------------------
# 3) Conjunto total de barras (reais + virtuais)
# ------------------------------------------------------------
# Criar conjuntos de barras incluindo virtuais
all_mt_buses = buses_mt + [trafo_MT_bus[tid] for tid in TR]
all_bt_buses = buses_bt + [trafo_BT_bus[tid] for tid in TR]

m.BUS_MT = pyo.Set(initialize=all_mt_buses,
                   doc="Barras MT (reais + virtuais)")
m.BUS_BT = pyo.Set(initialize=all_bt_buses,
                   doc="Barras BT (reais + virtuais)")


# ------------------------------------------------------------
# 4) Conjuntos Barra-Fase (incluindo virtuais)
# ------------------------------------------------------------
bus_ph_mt = [
    (int(row["N"]), ph)
    for _, row in df_buses_mt.iterrows()
    for ph in row["phase_list"]
]

for tid in TR:
    for ph in trafo_phases_dict[tid]:
        bus_ph_mt.append((trafo_MT_bus[tid], ph))

m.BUS_PH_MT = pyo.Set(
    dimen=2,
    initialize=sorted(set(bus_ph_mt)),
    doc="Barras-fase MT (incluindo virtuais)"
)


bus_ph_bt = [
    (int(row["N"]), ph)
    for _, row in df_buses_bt.iterrows()
    for ph in row["phase_list"]
]

for tid in TR:
    for ph in trafo_phases_dict[tid]:
        bus_ph_bt.append((trafo_BT_bus[tid], ph))

m.BUS_PH_BT = pyo.Set(
    dimen=2,
    initialize=sorted(set(bus_ph_bt)),
    doc="Barras-fase BT (incluindo virtuais)"
)


# ------------------------------------------------------------
# 5) Ramos
# ------------------------------------------------------------
m.BR_MT     = pyo.Set(initialize=branches_mt, doc="Ramos MT")
m.BR_BT     = pyo.Set(initialize=branches_bt, doc="Ramos BT")
m.BR_PH_MT  = pyo.Set(dimen=2, initialize=branch_phase_mt,
                      doc="Ramos-fase MT")
m.BR_PH_BT  = pyo.Set(dimen=2, initialize=branch_phase_bt,
                      doc="Ramos-fase BT")


# ------------------------------------------------------------
# 6) Transformadores
# ------------------------------------------------------------
m.TR    = pyo.Set(initialize=TR, doc="Transformadores")
m.TR_PH = pyo.Set(dimen=2, initialize=TR_PH,
                  doc="Transformadores por fase")


# ------------------------------------------------------------
# 7) Reguladores (SVR monofásicos independentes por fase)
# ------------------------------------------------------------
m.REG    = pyo.Set(initialize=REG, doc="Reguladores de tensão")
m.REG_PH = pyo.Set(dimen=2, initialize=REG_PH,
                   doc="Reguladores por fase (monofásicos)")


# ------------------------------------------------------------
# 8) Sistemas Fotovoltaicos (somente onde Sinv > 0)
# ------------------------------------------------------------
PV_BUS_PH = sorted([
    (b, ph)
    for (b, ph), S in Sinv_ph.items()
    if S > 0.0
])

m.PV_BUS_PH = pyo.Set(
    dimen=2,
    initialize=PV_BUS_PH,
    doc="Sistemas PV por barra-fase"
)

# Média Tensão

# Parâmetros dos ramos MT
m.R_MT = pyo.Param(m.BR_PH_MT, initialize=lambda model, br, ph: R_mt.get((br, ph), 0.0) / 1000.0,  within=pyo.NonNegativeReals)
m.X_MT = pyo.Param(m.BR_PH_MT, initialize=lambda model, br, ph: X_mt.get((br, ph), 0.0) / 1000.0, within=pyo.NonNegativeReals)
m.Z_sqr_MT = pyo.Param(m.BR_PH_MT, initialize=lambda model, br, ph: (R_mt.get((br, ph), 0.0)/1000.0)**2 + (X_mt.get((br, ph), 0.0)/1000.0)**2)

# Corrente máxima
Imax_dict_MT = {(br, ph): Imax_mt[br] for (br, ph) in m.BR_PH_MT}
m.I_max_MT = pyo.Param(m.BR_PH_MT, initialize=Imax_dict_MT, within=pyo.NonNegativeReals)

# Conexões dos ramos
m.from_bus_MT = pyo.Param(m.BR_MT, initialize=from_bus_mt)
m.to_bus_MT = pyo.Param(m.BR_MT, initialize=to_bus_mt)

# Tensão nominal e limites
m.Vnom_MT = pyo.Param(initialize=4.16/math.sqrt(3))  # kV VLN
m.V_min_MT = pyo.Param(initialize=0.93 * m.Vnom_MT)
m.V_max_MT = pyo.Param(initialize=1.05 * m.Vnom_MT)

# Cargas MT (zero por padrão)
m.Pd_MT = pyo.Param(m.BUS_PH_MT, m.T, initialize=0, within=pyo.Reals)
m.Qd_MT = pyo.Param(m.BUS_PH_MT, m.T, initialize=0, within=pyo.Reals)

# Identificação da barra slack
m.Tb = pyo.Param(m.BUS_MT,  initialize=lambda m, n: 1 if n == slack_bus else 0, doc="Barra slack/Subestação")


# Parametros Reguladores
# Conexões (barras MT reais)
m.reg_up_bus = pyo.Param(m.REG, initialize=reg_up_bus, within=pyo.Any)
m.reg_dn_bus = pyo.Param(m.REG, initialize=reg_dn_bus, within=pyo.Any)

# Passo do tap (pu/tap)
m.step_pu = pyo.Param(
    m.REG_PH,
    initialize=0.00625,
    within=pyo.PositiveReals
)

# Limites do tap (relaxado)
m.tap_min = pyo.Param(m.REG_PH, initialize=-16)
m.tap_max = pyo.Param(m.REG_PH, initialize=16)

# Setpoint e banda (pu)
m.Vreg_pu = pyo.Param(m.REG_PH, default=1.0, within=pyo.PositiveReals)
m.band_pu = pyo.Param(m.REG_PH, default=0.02, within=pyo.PositiveReals)

# LDC (por regulador)
m.R_LDC = pyo.Param(m.REG, initialize=3.0)
m.X_LDC = pyo.Param(m.REG, initialize=9.0)

# Base de tensão (kV)
m.Vbase_SVR_kV = pyo.Param(initialize=2.4)


# Capacidade aparente por fase (kVA)
m.Smax_REG_PH = pyo.Param(
    m.REG_PH,
    default=1e3,
    within=pyo.PositiveReals
)

# Eficiência (opcional)
m.eta_SVR = pyo.Param(initialize=0.999)

# Delay de tap
m.delay_steps = pyo.Param(initialize=int(math.ceil(15/DT_MIN)))  # 2

# Baixa Tensão

# Parâmetros dos ramos BT
m.R_BT = pyo.Param(m.BR_PH_BT,
                  initialize=lambda model, br, ph: R_bt.get((br, ph), 0.0) / 1000.0,
                  within=pyo.NonNegativeReals)
m.X_BT = pyo.Param(m.BR_PH_BT,
                  initialize=lambda model, br, ph: X_bt.get((br, ph), 0.0) / 1000.0,
                  within=pyo.NonNegativeReals)
m.Z_sqr_BT = pyo.Param(m.BR_PH_BT,
                      initialize=lambda model, br, ph: (R_bt.get((br, ph), 0.0)/1000.0)**2 +
                                                      (X_bt.get((br, ph), 0.0)/1000.0)**2)

# Corrente máxima BT
Imax_dict_BT = {(br, ph): Imax_bt[br] for (br, ph) in m.BR_PH_BT}
m.I_max_BT = pyo.Param(m.BR_PH_BT, initialize=Imax_dict_BT, within=pyo.NonNegativeReals)

# Conexões dos ramos BT
m.from_bus_BT = pyo.Param(m.BR_BT, initialize=from_bus_bt)
m.to_bus_BT = pyo.Param(m.BR_BT, initialize=to_bus_bt)

# Tensão nominal e limites BT
m.Vnom_BT = pyo.Param(initialize=0.480/math.sqrt(3))  # kV # VLN
m.V_min_BT = pyo.Param(initialize=0.93 * m.Vnom_BT)
m.V_max_BT = pyo.Param(initialize=1.05 * m.Vnom_BT)

# Cargas BT
m.Pd_BT = pyo.Param(m.BUS_PH_BT, m.T,
                   initialize=lambda m, b, ph, t: Pload_bt.get((b, ph), 0.0),
                   within=pyo.Reals)
m.Qd_BT = pyo.Param(m.BUS_PH_BT, m.T,
                   initialize=lambda m, b, ph, t: Qload_bt.get((b, ph), 0.0),
                   within=pyo.Reals)

# PV BT
# perfil simples (ex.: constante = 1)

# irr = {t:1.0 for t in T}

nT = len(T)
x_hour = np.linspace(0, 1, len(irr_hourly))
x_full = np.linspace(0, 1, nT)

irr_interp = np.interp(x_full, x_hour, irr_hourly)

irr_dict = {t: float(irr_interp[t]) for t in range(nT)}
m.irr = pyo.Param(m.T, initialize=irr_dict, within=pyo.NonNegativeReals)

m.Ppv_max = pyo.Param(m.BUS_PH_BT,
                      initialize=lambda m,b,ph: Ppv_max.get((b,ph), 0.0),
                      within=pyo.NonNegativeReals)


m.Sinv = pyo.Param(m.BUS_PH_BT,
                   initialize=lambda m,b,ph: Sinv_ph.get((b,ph), 0.0),
                   within=pyo.NonNegativeReals)


# 2) Parâmetros IEEE 1547 Cat B (default)
# ----------------------------
# Em pu:
VRef = 1.00
V1 = VRef - 0.08
V2 = VRef - 0.02
V3 = VRef + 0.02
V4 = VRef + 0.08

m.VV_V1 = pyo.Param(initialize=V1)
m.VV_V2 = pyo.Param(initialize=V2)
m.VV_V3 = pyo.Param(initialize=V3)
m.VV_V4 = pyo.Param(initialize=V4)

# Cat B default: |Q| = 0.44 * Snameplate (por fase, no seu modelo)
m.Qcap_frac = pyo.Param(initialize=0.44, within=pyo.PositiveReals)
# Adicao V2.2
# Qcap por (b,ph) em kVAr (coerente com sua base kVA)
def _qcap(m, b, ph):
    return m.Qcap_frac * m.Sinv[b, ph]
m.Qcap = pyo.Expression(m.PV_BUS_PH, rule=_qcap)


# Transformadores

# Barras virtuais dos transformadores
# Barras virtuais do transformador (nó intermediário)
m.tr_mv_bus = pyo.Param(m.TR, initialize=trafo_MT_bus,doc="Barra virtual do trafo no lado MT")
m.tr_lv_bus = pyo.Param(m.TR, initialize=trafo_BT_bus,doc="Barra virtual do trafo no lado BT")


# Barras reais conectadas aos transformadores
m.trafo_mt_real_bus = pyo.Param(m.TR, initialize=trafo_to_mt_bus,doc="Barra MT real conectada ao trafo")

m.trafo_bt_real_bus = pyo.Param(m.TR, initialize=trafo_to_bt_bus,doc="Barra BT real conectada ao trafo")

# Parâmetros técnicos dos transformadores
m.Pnom_TR = pyo.Param(m.TR, initialize=Pnom_TR, within=pyo.PositiveReals)
m.Pfe_TR = pyo.Param(m.TR, initialize=Pfe_TR, within=pyo.NonNegativeReals)
m.Pt_TR = pyo.Param(m.TR, initialize=Pt_TR, within=pyo.NonNegativeReals)
m.Pfe_TR_PH = pyo.Param(m.TR_PH, initialize=Pfe_TR_PH, within=pyo.NonNegativeReals)

# Coeficientes de perdas
m.alpha_tr = pyo.Param(m.TR_PH, initialize=alpha_tr, default=0.0)
m.beta_tr = pyo.Param(m.TR_PH, initialize=beta_tr, default=0.0)

# Potência nominal por fase
m.Snom_TR_PH = pyo.Param(m.TR_PH, initialize=Snom_TR_PH, within=pyo.NonNegativeReals)
m.Pcu_nom_TR_PH = pyo.Param(m.TR_PH, initialize=Pcu_TR_PH, within=pyo.NonNegativeReals)

# Número de fases por trafo
m.nph_TR = pyo.Param(m.TR, initialize=nph_TR, within=pyo.PositiveIntegers)
m.cos_phi = pyo.Param(initialize=0.92)
m.sin_phi = pyo.Param(initialize=math.sqrt(1.0 - pyo.value(m.cos_phi)**2),within=pyo.NonNegativeReals)



m.kv_mv_TR = pyo.Param(m.TR, initialize=kv_mv_dict, within=pyo.PositiveReals)
m.kv_lv_TR = pyo.Param(m.TR, initialize=kv_lv_dict, within=pyo.PositiveReals)

# Variáveis MT
m.I_SQR_MT = pyo.Var(m.BR_PH_MT, m.T, domain=pyo.NonNegativeReals)
m.V_SQR_MT = pyo.Var(m.BUS_PH_MT, m.T,
                     bounds=(m.V_min_MT ** 2, m.V_max_MT ** 2),
                     domain=pyo.NonNegativeReals,
                     initialize=m.Vnom_MT**2)

m.P_sub_MT = pyo.Var(m.BUS_PH_MT, m.T, domain=pyo.NonNegativeReals, initialize=0)
m.Q_sub_MT = pyo.Var(m.BUS_PH_MT, m.T, domain=pyo.NonNegativeReals, initialize=0)

m.P_fluxo_MT = pyo.Var(m.BR_PH_MT, m.T, domain=pyo.Reals)
m.Q_fluxo_MT = pyo.Var(m.BR_PH_MT, m.T, domain=pyo.Reals)
m.P_loss_MT = pyo.Var(m.BR_PH_MT, m.T, domain=pyo.NonNegativeReals, initialize=0)

# Variáveis BT
m.I_SQR_BT = pyo.Var(m.BR_PH_BT, m.T, domain=pyo.NonNegativeReals)
m.V_SQR_BT = pyo.Var(m.BUS_PH_BT, m.T,
                     bounds=(m.V_min_BT ** 2, m.V_max_BT ** 2),
                     domain=pyo.NonNegativeReals,
                     initialize=m.Vnom_BT**2)

m.P_fluxo_BT = pyo.Var(m.BR_PH_BT, m.T, domain=pyo.Reals)
m.Q_fluxo_BT = pyo.Var(m.BR_PH_BT, m.T, domain=pyo.Reals)
m.P_loss_BT = pyo.Var(m.BR_PH_BT, m.T, domain=pyo.NonNegativeReals, initialize=0)
# Variavel de carga cortada
m.Pshed_BT = pyo.Var(m.BUS_PH_BT, m.T, domain=pyo.NonNegativeReals)

# Variáveis PV
# Potência ativa PV variável (kW)
def ppv_bounds(model, b, ph, t):
    return (0.0, m.Ppv_max[b, ph] * m.irr[t])

m.Ppv = pyo.Var(m.PV_BUS_PH, m.T, bounds=ppv_bounds)


m.Qpv = pyo.Var(m.PV_BUS_PH, m.T, domain=pyo.Reals)


# v_pu por (b,ph,t) apenas onde há PV
m.Vpv_pu_sqr = pyo.Var(
    m.PV_BUS_PH, m.T,
    domain=pyo.NonNegativeReals,
    bounds=lambda m,b,ph,t: (
        (m.V_min_BT / m.Vnom_BT)**2,
        (m.V_max_BT / m.Vnom_BT)**2
    )
)


# Variáveis dos transformadores
m.Ptr_pos = pyo.Var(m.TR_PH, m.T, domain=pyo.NonNegativeReals)
m.Ptr_neg = pyo.Var(m.TR_PH, m.T, domain=pyo.NonNegativeReals)
m.Qtr_pos = pyo.Var(m.TR_PH, m.T, domain=pyo.NonNegativeReals)
m.Qtr_neg = pyo.Var(m.TR_PH, m.T, domain=pyo.NonNegativeReals)

m.Ptr = pyo.Var(m.TR_PH, m.T, domain=pyo.Reals)
m.Qtr = pyo.Var(m.TR_PH, m.T, domain=pyo.Reals)

m.P_loss_CU = pyo.Var(m.TR_PH, m.T, domain=pyo.NonNegativeReals)
m.P_loss_TR = pyo.Var(m.TR_PH, m.T,domain=pyo.NonNegativeReals, doc="Perdas ativas totais do transformador por fase")

m.Qloss_tr = pyo.Var(m.TR_PH, m.T, domain=pyo.NonNegativeReals)

# Variáveis de conexão entre barras reais e virtuais
m.P_fluxo_mt_to_trafo = pyo.Var(m.TR_PH, m.T, domain=pyo.Reals, doc="Fluxo ativo MT real -> barra virtual do trafo")

m.P_fluxo_trafo_to_bt = pyo.Var(m.TR_PH, m.T,domain=pyo.Reals, doc="Fluxo ativo barra virtual do trafo -> BT real")

m.Q_fluxo_mt_to_trafo = pyo.Var(m.TR_PH, m.T, domain=pyo.Reals, doc="Q da MT real -> nó virtual trafo")
m.Q_fluxo_trafo_to_bt = pyo.Var(m.TR_PH, m.T, domain=pyo.Reals, doc="Q do nó virtual trafo -> BT real")

m.Ptr_bt = pyo.Var(m.TR_PH, m.T, domain=pyo.Reals, doc="Potência ativa entregue à BT (pós-perdas)")
m.Qtr_bt = pyo.Var(m.TR_PH, m.T, domain=pyo.Reals, doc="Potência reativa entregue à BT (pós-perdas)")
# Variaveis Reguladores

# Tap discreto (inteiro)
m.tap = pyo.Var(
    m.REG_PH, m.T,
    domain=pyo.Integers,
    bounds=lambda m,r,p,t: (m.tap_min[r,p], m.tap_max[r,p])
)

# Binária para identificar mudança de tap
m.delta_tap = pyo.Var(m.REG_PH, m.T, domain=pyo.Binary)

# Potência pelo SVR
m.P_svr = pyo.Var(m.REG_PH, m.T)
m.Q_svr = pyo.Var(m.REG_PH, m.T)

# Fluxos internos (entrada/saída)
m.P_svr_in  = pyo.Var(m.REG_PH, m.T)
m.P_svr_out = pyo.Var(m.REG_PH, m.T)
m.Q_svr_in  = pyo.Var(m.REG_PH, m.T)
m.Q_svr_out = pyo.Var(m.REG_PH, m.T)

# Tensões auxiliares (kV)
m.V_dn_kV  = pyo.Var(m.REG_PH, m.T, domain=pyo.NonNegativeReals)
m.V_est_kV = pyo.Var(m.REG_PH, m.T)

# Banda soft
m.v_slack_over  = pyo.Var(m.REG_PH, m.T, domain=pyo.NonNegativeReals)
m.v_slack_under = pyo.Var(m.REG_PH, m.T, domain=pyo.NonNegativeReals)

# Injeções equivalentes no balanço MT
m.P_inj_svr_MT = pyo.Var(m.BUS_PH_MT, m.T, initialize=0.0)
m.Q_inj_svr_MT = pyo.Var(m.BUS_PH_MT, m.T, initialize=0.0)

# Variaveis auxiliares
m.S_sqr_MT = pyo.Var(m.BR_PH_MT, m.T, domain=pyo.NonNegativeReals)
m.S_sqr_BT = pyo.Var(m.BR_PH_BT, m.T, domain=pyo.NonNegativeReals)

# Condições da barra slack
for (i, ph) in m.BUS_PH_MT:
    if i == slack_bus:  # Barra slack MT
        for t in m.T:
            m.V_SQR_MT[i, ph, t].fix(m.Vnom_MT**2)


# -----------------------------
# 1) SPLIT (para módulo) no fluxo de entrada do trafo
#    (se você já tem Ptr_pos/Ptr_neg etc, REUSE com novo significado)
# -----------------------------
def _pin_split(m, tid, ph, t):
    # Reinterpreta Ptr como "P_in" (apenas se você quiser manter Ptr como auxiliar).
    # Se quiser ZERO Ptr, comente as duas linhas abaixo e use diretamente P_fluxo_*.
    return m.P_fluxo_mt_to_trafo[tid, ph, t] == m.Ptr_pos[tid, ph, t] - m.Ptr_neg[tid, ph, t]

def _qin_split(m, tid, ph, t):
    return m.Q_fluxo_mt_to_trafo[tid, ph, t] == m.Qtr_pos[tid, ph, t] - m.Qtr_neg[tid, ph, t]

m.TR_Pin_split = pyo.Constraint(m.TR_PH, m.T, rule=_pin_split)
m.TR_Qin_split = pyo.Constraint(m.TR_PH, m.T, rule=_qin_split)

# -----------------------------
# 2) LIMITE DE POTÊNCIA (na ENTRADA do trafo, por fase)
#    Isomórfico: limita o "link de entrada"
# -----------------------------
def tr_P_rating_rule(m, tid, ph, t):
    # |P_in| <= Snom*cosphi  (proxy, igual seu)
    return m.Ptr_pos[tid, ph, t] + m.Ptr_neg[tid, ph, t] <= m.Snom_TR_PH[tid, ph] * m.cos_phi

# def tr_Q_rating_rule(m, tid, ph, t):
#     # |Q_in| <= Snom*sinphi (proxy)
#     sinphi = (max(0.0, 1.0 - float(pyo.value(m.cos_phi))**2))**0.5
#     return m.Qtr_pos[tid, ph, t] + m.Qtr_neg[tid, ph, t] <= m.Snom_TR_PH[tid, ph] * sinphi


def tr_Q_rating_rule(m, tid, ph, t):
    return (
        m.Qtr_pos[tid, ph, t] + m.Qtr_neg[tid, ph, t]
        <= m.Snom_TR_PH[tid, ph] * m.sin_phi
    )

m.TR_P_rating = pyo.Constraint(m.TR_PH, m.T, rule=tr_P_rating_rule)
m.TR_Q_rating = pyo.Constraint(m.TR_PH, m.T, rule=tr_Q_rating_rule)



# -----------------------------
# 3) PERDAS ATIVAS (cobre + total)
#    Isomórfico ao seu CE: perdas ~ (|P_in|/Pnom)^2
# -----------------------------
def perdas_cobre_trafo_rule(m, tid, ph, t):
    Pabs = m.Ptr_pos[tid, ph, t] + m.Ptr_neg[tid, ph, t]
    k = m.Pcu_nom_TR_PH[tid, ph] / (m.Snom_TR_PH[tid, ph] * m.cos_phi)**2
    return m.P_loss_CU[tid, ph, t] == k * Pabs**2


def perdas_totais_trafo_rule(m, tid, ph, t):
    return m.P_loss_TR[tid, ph, t] == m.Pfe_TR_PH[tid, ph] + m.P_loss_CU[tid, ph, t]

m.TR_Ploss_cu  = pyo.Constraint(m.TR_PH, m.T, rule=perdas_cobre_trafo_rule)
m.TR_Ploss_tot = pyo.Constraint(m.TR_PH, m.T, rule=perdas_totais_trafo_rule)



# Perdas reativas do trafo (heurística).
#     Atenção: beta_tr é proxy. Se isso estiver matando a factibilidade,
#     comente este bloco e fixe Qloss_tr=0.
def perdas_reativas_trafo_rule(m, tid, ph, t):
    Pabs = m.Ptr_pos[tid, ph, t] + m.Ptr_neg[tid, ph, t]
    kq = m.beta_tr[tid, ph] / (m.Snom_TR_PH[tid, ph] * m.cos_phi)**2
    return m.Qloss_tr[tid, ph, t] == kq * Pabs**2


m.TR_Qloss = pyo.Constraint(m.TR_PH, m.T, rule=perdas_reativas_trafo_rule)

def balance_traf_P_rule(m, tid, ph, t):
    return (
        m.P_fluxo_mt_to_trafo[tid, ph, t]
        == m.P_fluxo_trafo_to_bt[tid, ph, t] + m.P_loss_TR[tid, ph, t]
    )

def balance_traf_Q_rule(m, tid, ph, t):
    return (
        m.Q_fluxo_mt_to_trafo[tid, ph, t]
        == m.Q_fluxo_trafo_to_bt[tid, ph, t] + m.Qloss_tr[tid, ph, t]
    )

m.TR_balance_P = pyo.Constraint(m.TR_PH, m.T, rule=balance_traf_P_rule)
m.TR_balance_Q = pyo.Constraint(m.TR_PH, m.T, rule=balance_traf_Q_rule)


def tr_vratio_rule(m, tid, ph, t):
    mt_real = m.trafo_mt_real_bus[tid]
    bt_real = m.trafo_bt_real_bus[tid]

    if (mt_real, ph) not in m.BUS_PH_MT or (bt_real, ph) not in m.BUS_PH_BT:
        return pyo.Constraint.Skip

    a = m.kv_lv_TR[tid] / m.kv_mv_TR[tid]  # razão de tensão (BT/MT)
    return m.V_SQR_BT[bt_real, ph, t] == (a**2) * m.V_SQR_MT[mt_real, ph, t]

m.TR_Vratio = pyo.Constraint(m.TR_PH, m.T, rule=tr_vratio_rule)

bus_ph_active_mt = set()
bus_ph_active_bt = set()

# MT – ramos
for (br, ph) in m.BR_PH_MT:
    bus_ph_active_mt.add((m.from_bus_MT[br], ph))
    bus_ph_active_mt.add((m.to_bus_MT[br],   ph))

# MT – trafos (lado real)
for (tid, ph) in m.TR_PH:
    bus_ph_active_mt.add((m.trafo_mt_real_bus[tid], ph))

# Slack MT
for ph in m.PH:
    bus_ph_active_mt.add((slack_bus, ph))

# BT – ramos
for (br, ph) in m.BR_PH_BT:
    bus_ph_active_bt.add((m.from_bus_BT[br], ph))
    bus_ph_active_bt.add((m.to_bus_BT[br],   ph))

# BT – trafos (lado real)
for (tid, ph) in m.TR_PH:
    bus_ph_active_bt.add((m.trafo_bt_real_bus[tid], ph))


# Com SVR
def pbal_mt_rule(m, bus, ph, t):
    if (bus, ph) not in bus_ph_active_mt:
        return pyo.Constraint.Skip

    inflow = sum(m.P_fluxo_MT[br, ph, t] for (br,p) in m.BR_PH_MT if p==ph and m.to_bus_MT[br]==bus)
    outflow= sum(m.P_fluxo_MT[br, ph, t] for (br,p) in m.BR_PH_MT if p==ph and m.from_bus_MT[br]==bus)

    slack = m.P_sub_MT[bus, ph, t] if m.Tb[bus]==1 else 0.0
    load  = m.Pd_MT[bus, ph, t]

    to_trafos = sum(
        m.P_fluxo_mt_to_trafo[tid, ph, t]
        for tid in m.TR
        if (tid, ph) in m.TR_PH and m.trafo_mt_real_bus[tid] == bus
    )

    return inflow - outflow + slack - load - to_trafos + m.P_inj_svr_MT[bus, ph, t] == 0.0

def qbal_mt_rule(m, bus, ph, t):
    if (bus, ph) not in bus_ph_active_mt:
        return pyo.Constraint.Skip

    inflow = sum(m.Q_fluxo_MT[br, ph, t] for (br,p) in m.BR_PH_MT if p==ph and m.to_bus_MT[br]==bus)
    outflow= sum(m.Q_fluxo_MT[br, ph, t] for (br,p) in m.BR_PH_MT if p==ph and m.from_bus_MT[br]==bus)

    slack = m.Q_sub_MT[bus, ph, t] if m.Tb[bus]==1 else 0.0
    load  = m.Qd_MT[bus, ph, t]

    to_trafos = sum(
        m.Q_fluxo_mt_to_trafo[tid, ph, t]
        for tid in m.TR
        if (tid, ph) in m.TR_PH and m.trafo_mt_real_bus[tid] == bus
    )

    return inflow - outflow + slack - load - to_trafos + m.Q_inj_svr_MT[bus, ph, t] == 0.0

m.MT_Pbal = pyo.Constraint(m.BUS_PH_MT, m.T, rule=pbal_mt_rule)
m.MT_Qbal = pyo.Constraint(m.BUS_PH_MT, m.T, rule=qbal_mt_rule)





# V2 PV
# ============================================================
# (iii) SUBSTITUIÇÃO DIRETA NO pbal_bt_rule (sem quebrar o resto)
#     Só muda: pv = m.Ppv[bus,ph,t] (antes era m.Ppv[bus,ph])
# ============================================================
def pbal_bt_rule(m, bus, ph, t):

    if (bus, ph) not in bus_ph_active_bt:
        return pyo.Constraint.Skip

    inflow = sum(
        m.P_fluxo_BT[br, ph, t]
        for (br, p) in m.BR_PH_BT
        if p == ph and m.to_bus_BT[br] == bus
    )

    outflow = sum(
        m.P_fluxo_BT[br, ph, t]
        for (br, p) in m.BR_PH_BT
        if p == ph and m.from_bus_BT[br] == bus
    )

    load = m.Pd_BT[bus, ph, t]

    if (bus, ph) in m.PV_BUS_PH:
        pv = m.Ppv[bus, ph, t]
    else:
        pv = 0.0

    from_trafos = sum(
        m.P_fluxo_trafo_to_bt[tid, ph, t]
        for tid in m.TR
        if (tid, ph) in m.TR_PH and m.trafo_bt_real_bus[tid] == bus
    )

    return inflow - outflow + from_trafos + pv - load == 0.0


# sobrescreve/define
m.BT_Pbal = pyo.Constraint(m.BUS_PH_BT, m.T, rule=pbal_bt_rule)


def qbal_bt_rule(m, bus, ph, t):

    if (bus, ph) not in bus_ph_active_bt:
        return pyo.Constraint.Skip

    inflow = sum(
        m.Q_fluxo_BT[br, ph, t]
        for (br, p) in m.BR_PH_BT
        if p == ph and m.to_bus_BT[br] == bus
    )

    outflow = sum(
        m.Q_fluxo_BT[br, ph, t]
        for (br, p) in m.BR_PH_BT
        if p == ph and m.from_bus_BT[br] == bus
    )

    load = m.Qd_BT[bus, ph, t]
    if (bus, ph) in m.PV_BUS_PH:
        pv = m.Qpv[bus, ph,t]
    else:
        pv = 0.0

    from_trafos = sum(
        m.Q_fluxo_trafo_to_bt[tid, ph, t]
        for tid in m.TR
        if (tid, ph) in m.TR_PH and m.trafo_bt_real_bus[tid] == bus
    )

    return inflow - outflow + from_trafos + pv - load == 0.0

m.BT_Qbal = pyo.Constraint(m.BUS_PH_BT, m.T, rule=qbal_bt_rule)

# Queda de tensão

def mt_vdrop_rule(model, br, ph, t):
    i = m.from_bus_MT[br]
    j = m.to_bus_MT[br]

    if (i, ph) not in m.BUS_PH_MT or (j, ph) not in m.BUS_PH_MT:
        return pyo.Constraint.Skip

    return m.V_SQR_MT[j, ph, t] == (
        m.V_SQR_MT[i, ph, t]
        - 2 * (m.R_MT[br, ph] * m.P_fluxo_MT[br, ph, t] +
               m.X_MT[br, ph] * m.Q_fluxo_MT[br, ph, t])
        + m.Z_sqr_MT[br, ph] * m.I_SQR_MT[br, ph, t]
    )

def bt_vdrop_rule(model, br, ph, t):
    i = m.from_bus_BT[br]
    j = m.to_bus_BT[br]

    if (i, ph) not in m.BUS_PH_BT or (j, ph) not in m.BUS_PH_BT:
        return pyo.Constraint.Skip

    return m.V_SQR_BT[j, ph, t] == (
        m.V_SQR_BT[i, ph, t]
        - 2 * (m.R_BT[br, ph] * m.P_fluxo_BT[br, ph, t] +
               m.X_BT[br, ph] * m.Q_fluxo_BT[br, ph, t])
        + m.Z_sqr_BT[br, ph] * m.I_SQR_BT[br, ph, t]
    )

m.MT_Vdrop = pyo.Constraint(m.BR_PH_MT, m.T, rule=mt_vdrop_rule)
m.BT_Vdrop = pyo.Constraint(m.BR_PH_BT, m.T, rule=bt_vdrop_rule)

# MT
def mt_flow_rule(m, br, ph, t):
    i = m.from_bus_MT[br]
    if (i, ph) not in m.BUS_PH_MT:
        return pyo.Constraint.Skip

    return (
        m.S_sqr_MT[br, ph, t] >=
        m.P_fluxo_MT[br, ph, t]**2 + m.Q_fluxo_MT[br, ph, t]**2
    )

# BT
def bt_flow_rule(m, br, ph, t):
    i = m.from_bus_BT[br]
    if (i, ph) not in m.BUS_PH_BT:
        return pyo.Constraint.Skip

    return (
        m.S_sqr_BT[br, ph, t] >=
        m.P_fluxo_BT[br, ph, t]**2 + m.Q_fluxo_BT[br, ph, t]**2
    )


# MT
def mt_cone_rule(m, br, ph, t):
    i = m.from_bus_MT[br]
    if (i, ph) not in m.BUS_PH_MT:
        return pyo.Constraint.Skip

    return (
        m.S_sqr_MT[br, ph, t]
        <= m.V_SQR_MT[i, ph, t] * m.I_SQR_MT[br, ph, t]
    )

# BT
def bt_cone_rule(m, br, ph, t):
    i = m.from_bus_BT[br]
    if (i, ph) not in m.BUS_PH_BT:
        return pyo.Constraint.Skip

    return (
        m.S_sqr_BT[br, ph, t]
        <= m.V_SQR_BT[i, ph, t] * m.I_SQR_BT[br, ph, t]
    )

m.fluxo_potencia_mt = pyo.Constraint(m.BR_PH_MT, m.T, rule=mt_flow_rule)
m.fluxo_potencia_bt = pyo.Constraint(m.BR_PH_BT, m.T, rule=bt_flow_rule)
m.mt_cone_rule = pyo.Constraint(m.BR_PH_MT, m.T, rule=mt_cone_rule)
m.bt_cone_rule = pyo.Constraint(m.BR_PH_BT, m.T, rule=bt_cone_rule)

# Perdas nas linhas
def perdas_mt_rule(model, br, ph, t):
    return m.P_loss_MT[br, ph, t] == m.R_MT[br, ph] * m.I_SQR_MT[br, ph, t]

def perdas_bt_rule(model, br, ph, t):
    return m.P_loss_BT[br, ph, t] == m.R_BT[br, ph] * m.I_SQR_BT[br, ph, t]

m.perdas_mt = pyo.Constraint(m.BR_PH_MT, m.T, rule=perdas_mt_rule)
m.perdas_bt = pyo.Constraint(m.BR_PH_BT, m.T, rule=perdas_bt_rule)

# Limites de corrente
def i_max_mt_rule(model, br, ph, t):
    return m.I_SQR_MT[br, ph, t] <= m.I_max_MT[br, ph]**2

def i_max_bt_rule(model, br, ph, t):
    return m.I_SQR_BT[br, ph, t] <= m.I_max_BT[br, ph]**2

m.i_max_mt = pyo.Constraint(m.BR_PH_MT, m.T, rule=i_max_mt_rule)
m.i_max_bt = pyo.Constraint(m.BR_PH_BT, m.T, rule=i_max_bt_rule)

#
# Conversação de potencia (ideal ou quase ideal)
def svr_balance_P(m, rid, ph, t):
    return m.P_svr_out[rid, ph, t] == m.eta_SVR * m.P_svr_in[rid, ph, t]

def svr_balance_Q(m, rid, ph, t):
    return m.Q_svr_out[rid, ph, t] == m.Q_svr_in[rid, ph, t]

m.SVR_Pbalance = pyo.Constraint(m.REG_PH, m.T, rule=svr_balance_P)
m.SVR_Qbalance = pyo.Constraint(m.REG_PH, m.T, rule=svr_balance_Q)



# (i) Relação tap–tensão: linearizar o produto V_SQR * tap (tap inteiro) via McCormick
# usar isto
m.WtapV = pyo.Var(
    m.REG_PH, m.T,
    domain=pyo.Reals,
    bounds=lambda m,rid,ph,t: (
        min(m.tap_min[rid,ph]*(m.V_min_MT**2), m.tap_min[rid,ph]*(m.V_max_MT**2),
            m.tap_max[rid,ph]*(m.V_min_MT**2), m.tap_max[rid,ph]*(m.V_max_MT**2)),
        max(m.tap_min[rid,ph]*(m.V_min_MT**2), m.tap_min[rid,ph]*(m.V_max_MT**2),
            m.tap_max[rid,ph]*(m.V_min_MT**2), m.tap_max[rid,ph]*(m.V_max_MT**2))
    )
)

def WtapV_mcc1(m, rid, ph, t):
    i = m.reg_up_bus[rid]
    xL, xU = m.tap_min[rid, ph], m.tap_max[rid, ph]
    yL, yU = m.V_min_MT**2, m.V_max_MT**2
    x, y, w = m.tap[rid, ph, t], m.V_SQR_MT[i, ph, t], m.WtapV[rid, ph, t]
    return w >= xL*y + yL*x - xL*yL
def WtapV_mcc2(m, rid, ph, t):
    i = m.reg_up_bus[rid]
    xL, xU = m.tap_min[rid, ph], m.tap_max[rid, ph]
    yL, yU = m.V_min_MT**2, m.V_max_MT**2
    x, y, w = m.tap[rid, ph, t], m.V_SQR_MT[i, ph, t], m.WtapV[rid, ph, t]
    return w >= xU*y + yU*x - xU*yU
def WtapV_mcc3(m, rid, ph, t):
    i = m.reg_up_bus[rid]
    xL, xU = m.tap_min[rid, ph], m.tap_max[rid, ph]
    yL, yU = m.V_min_MT**2, m.V_max_MT**2
    x, y, w = m.tap[rid, ph, t], m.V_SQR_MT[i, ph, t], m.WtapV[rid, ph, t]
    return w <= xU*y + yL*x - xU*yL
def WtapV_mcc4(m, rid, ph, t):
    i = m.reg_up_bus[rid]
    xL, xU = m.tap_min[rid, ph], m.tap_max[rid, ph]
    yL, yU = m.V_min_MT**2, m.V_max_MT**2
    x, y, w = m.tap[rid, ph, t], m.V_SQR_MT[i, ph, t], m.WtapV[rid, ph, t]
    return w <= xL*y + yU*x - xL*yU

m.WtapV_MCC1 = pyo.Constraint(m.REG_PH, m.T, rule=WtapV_mcc1)
m.WtapV_MCC2 = pyo.Constraint(m.REG_PH, m.T, rule=WtapV_mcc2)
m.WtapV_MCC3 = pyo.Constraint(m.REG_PH, m.T, rule=WtapV_mcc3)
m.WtapV_MCC4 = pyo.Constraint(m.REG_PH, m.T, rule=WtapV_mcc4)

def svr_vratio_rule(m, rid, ph, t):
    i = m.reg_up_bus[rid]
    j = m.reg_dn_bus[rid]
    if (i, ph) not in m.BUS_PH_MT or (j, ph) not in m.BUS_PH_MT:
        return pyo.Constraint.Skip
    k = 2 * m.step_pu[rid, ph]
    return m.V_SQR_MT[j, ph, t] == m.V_SQR_MT[i, ph, t] + k * m.WtapV[rid, ph, t]
m.SVR_Vratio = pyo.Constraint(m.REG_PH, m.T, rule=svr_vratio_rule)

# (ii) LDC: remover divisão (CPLEX não aceita). Fixar V_est_kV = V_dn_kV
def svr_ldc_rule(m, rid, ph, t):
    return m.V_est_kV[rid, ph, t] == m.V_dn_kV[rid, ph, t]
m.SVR_LDC = pyo.Constraint(m.REG_PH, m.T, rule=svr_ldc_rule)

# (iii) Mudança de tap com binária delta_tap (|tap_t - tap_{t-1}| <= M*delta_tap)
def tap_change_rule(m, rid, ph, t):
    if t == 0:
        return pyo.Constraint.Skip
    M = m.tap_max[rid, ph] - m.tap_min[rid, ph]
    return (-M*m.delta_tap[rid, ph, t] <= m.tap[rid, ph, t] - m.tap[rid, ph, t-1])
def tap_change_rule2(m, rid, ph, t):
    if t == 0:
        return pyo.Constraint.Skip
    M = m.tap_max[rid, ph] - m.tap_min[rid, ph]
    return (m.tap[rid, ph, t] - m.tap[rid, ph, t-1] <= M*m.delta_tap[rid, ph, t])

m.SVR_TapChange1 = pyo.Constraint(m.REG_PH, m.T, rule=tap_change_rule)
m.SVR_TapChange2 = pyo.Constraint(m.REG_PH, m.T, rule=tap_change_rule2)

# (iv) Capacidade do SVR: usar SOCP (cone rotacionado) com variável auxiliar
m.S_svr_sqr = pyo.Var(m.REG_PH, m.T, domain=pyo.NonNegativeReals)
def svr_scap1(m, rid, ph, t):
    return m.S_svr_sqr[rid, ph, t] >= m.P_svr[rid, ph, t]**2 + m.Q_svr[rid, ph, t]**2
def svr_scap2(m, rid, ph, t):
    return m.S_svr_sqr[rid, ph, t] <= m.Smax_REG_PH[rid, ph]**2
m.SVR_Scap1 = pyo.Constraint(m.REG_PH, m.T, rule=svr_scap1)
m.SVR_Scap2 = pyo.Constraint(m.REG_PH, m.T, rule=svr_scap2)

# ============================================================
# PV VOLT-VAR (CPLEX-friendly)
# ============================================================




def vv_vpu_sqr_def_rule(m, b, ph, t):
    return m.Vpv_pu_sqr[b, ph, t] * (m.Vnom_BT**2) == m.V_SQR_BT[b, ph, t]

m.VV_VpuSqrDef = pyo.Constraint(m.PV_BUS_PH, m.T, rule=vv_vpu_sqr_def_rule)


# ------------------------------------------------------------
# (2) Qcap
# ------------------------------------------------------------
if hasattr(m, "Qcap"):
    m.del_component(m.Qcap)

def qcap_rule(m, b, ph):
    return m.Qcap_frac * m.Sinv[b, ph]

m.Qcap = pyo.Expression(m.PV_BUS_PH, rule=qcap_rule)


# ------------------------------------------------------------
# (3) Breakpoints fixos (lista, não função)
# ------------------------------------------------------------
pw_pts = [
    pyo.value(m.VV_V1)**2,
    pyo.value(m.VV_V2)**2,
    pyo.value(m.VV_V3)**2,
    pyo.value(m.VV_V4)**2
]


def pw_q_rule(m, b, ph, t, x):
    Qcap = m.Qcap[b, ph]

    if x == pw_pts[0]:
        return Qcap
    elif x == pw_pts[1]:
        return 0.0
    elif x == pw_pts[2]:
        return 0.0
    else:
        return -Qcap

m.VV_Qcmd = pyo.Piecewise(
    m.PV_BUS_PH, m.T,
    m.Qpv,
    m.Vpv_pu_sqr,
    pw_pts=pw_pts,
    f_rule=pw_q_rule,
    pw_constr_type="EQ",
    pw_repn="SOS2"
)


# ------------------------------------------------------------
# (4) Saturação |Q| <= Qcap
# ------------------------------------------------------------
def qcap_upper(m, b, ph, t):
    return m.Qpv[b, ph, t] <= m.Qcap[b, ph]

def qcap_lower(m, b, ph, t):
    return m.Qpv[b, ph, t] >= -m.Qcap[b, ph]

m.QcapUpper = pyo.Constraint(m.PV_BUS_PH, m.T, rule=qcap_upper)
m.QcapLower = pyo.Constraint(m.PV_BUS_PH, m.T, rule=qcap_lower)


# ------------------------------------------------------------
# (5) Limite físico circular (MIQCP convexo)
# ------------------------------------------------------------
def pv_slimit_rule(m, b, ph, t):
    S = m.Sinv[b, ph]
    return m.Ppv[b, ph, t]**2 + m.Qpv[b, ph, t]**2 <= S**2

m.PV_Slimit = pyo.Constraint(m.PV_BUS_PH, m.T, rule=pv_slimit_rule)

# ============================================================
# OBJETIVO FINAL – CPLEX (com tap binário delta_tap)
# Prioridade:
#   1) Minimizar mudança de tap (delta_tap = 1)
#   2) Minimizar esforço reativo dos PVs
# Sem perdas na FO
# ============================================================

# ------------------------------------------------------------
# Pesos (hierarquia forte)
# ------------------------------------------------------------
W_TAP = 1e6   # MUITO maior → evita mudar tap
W_QPV = 1e1   # PV injeta Q antes de mudar tap


# ------------------------------------------------------------
# Função objetivo
# ------------------------------------------------------------
def objective_rule(m):

    # (A) Número de mudanças de tap (binária)
    tap_operations = sum(
        m.delta_tap[rid, ph, t]
        for (rid, ph) in m.REG_PH
        for t in m.T
    )

    # (B) Esforço reativo dos PVs (MIQP convexo)
    q_effort = sum(
        m.Qpv[b, ph, t]**2
        for (b, ph) in m.PV_BUS_PH
        for t in m.T
    )

    return (
        W_TAP * tap_operations
        + W_QPV * q_effort
    )

m.objective = pyo.Objective(rule=objective_rule, sense=pyo.minimize)

import os
from pyomo.environ import SolverFactory

# Caminho absoluto para o executável
cplex_path = "/opt/ibm/ILOG/CPLEX_Studio_Community2212/cplex/bin/x86-64_linux/cplex"

# Verifica se o arquivo existe e é executável
if os.path.exists(cplex_path):
    print(f"CPLEX encontrado em: {cplex_path}")

    # Garante que é executável
    !chmod +x /opt/ibm/ILOG/CPLEX_Studio_Community2212/cplex/bin/x86-64_linux/cplex

    # Cria o solver com caminho explícito
    opt = SolverFactory('cplex', executable=cplex_path)

    # Verifica disponibilidade
    print(f"Solver disponível: {opt.available()}")

    # Tenta resolver
    if opt.available():
        results = opt.solve(m, tee=True, options={'max_iter': 10000})
    else:
        print("Ainda não disponível. Tentando método alternativo...")
else:
    print(f"Arquivo não encontrado em: {cplex_path}")

import pyomo.environ as pyo

solver = pyo.SolverFactory("cplex")

results = solver.solve(m, tee=True)

from pyomo.environ import value

for rid in m.REG:
    total_ops = sum(
        value(m.delta_tap[rid, ph, t])
        for ph in m.PH
        for t in m.T
        if (rid, ph) in m.REG_PH
    )
    print(f"SVR {rid}: {int(round(total_ops))} operações")

for (rid, ph) in m.REG_PH:
    ops = sum(
        value(m.delta_tap[rid, ph, t])
        for t in m.T
    )
    print(f"SVR {rid} fase {ph}: {int(round(ops))} operações")

for (rid, ph) in m.REG_PH:
    for t in m.T:
        if value(m.delta_tap[rid, ph, t]) > 0.5:
            print(f"SVR {rid} fase {ph} operou no tempo {t}")

